package com.imperium.ims.mapper;

import com.imperium.ims.dto.CreateInvitationRequest;
import com.imperium.ims.dto.InvitationResponse;
import com.imperium.ims.entity.Invitation;
import org.mapstruct.*;

/**
 * MapStruct mapper for {@link Invitation} ↔ DTO conversions.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE, builder = @Builder(disableBuilder = true))
public interface InvitationMapper {

    @Mapping(target = "eventId",    source = "event.id")
    @Mapping(target = "eventTitle", source = "event.title")
    InvitationResponse toResponse(Invitation invitation);

    @Mapping(target = "id",     ignore = true)
    @Mapping(target = "event",  ignore = true)  // Resolved by service
    @Mapping(target = "token",  ignore = true)  // Generated by service
    @Mapping(target = "status", ignore = true)
    Invitation toEntity(CreateInvitationRequest request);
}
