ALTER TABLE otp_tokens ADD COLUMN attempts INT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS otp_verification_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    otp VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempt_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
